name: 'citypulse'
version: '1.0.0'
config-version: 2
require-dbt-version: ">=1.9.2"

profile: 'citypulse'

analysis-paths: ["analyses"]
asset-paths: ["assets"]
docs-paths: ["docs"]
macro-paths: ["macros"]
model-paths: ["models"]
test-paths: ["tests"]
seed-paths: ["seeds"]
snapshot-paths: ["snapshots"]
packages-install-path: "dbt_packages"

target-path: "target"
clean-targets:
  - "target"
  - "dbt_packages"
  - "logs"

models:
  citypulse:
    ingestion:
      yelp:
        +materialized: view
        +database: raw
        +schema: yelp
        +query_tag: yelp_ingestion
