disable_anonymized_analytics: False

gateways:
  sfprod:
    connection:
      # For more information on configuring the connection to your execution engine, visit:
      # https://sqlmesh.readthedocs.io/en/stable/reference/configuration/#connections
      # https://sqlmesh.readthedocs.io/en/stable/integrations/engines/snowflake/#connection-options
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}
      user: {{ env_var('SNOWFLAKE_USER') }}
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE') }}
      database: demo_sqlmesh
      role: accountadmin
      # authenticator: 
      # token: 
      # application: Tobiko_SQLMesh
      # private_key: 
      # private_key_path: 
      # private_key_passphrase: 
      # session_parameters: 
      concurrent_tasks: 4
      register_comments: True
      pre_ping: False
      pretty_sql: False
    state_connection:
      type: duckdb
      database: sf_state.db


default_gateway: sfprod

model_defaults:
  dialect: snowflake
  start: 2025-03-18
