disable_anonymized_analytics: False

gateways:
  sfprod:
    connection:
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}
      user: {{ env_var('SNOWFLAKE_USER') }}
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE') }}
      database: sqlmesh
      role: accountadmin
      concurrent_tasks: 4
      register_comments: True
      pre_ping: False
      pretty_sql: False
    state_connection:
      type: postgres
      host: {{ env_var('SUPABASE_HOST') }}
      user: {{ env_var('SUPABASE_USER') }}
      password: {{ env_var('SUPABASE_PASSWORD') }}
      port: {{ env_var('SUPABASE_PORT') | int }}
      database: {{ env_var('SUPABASE_DB') }}
  sfanalytics:
    connection:
      type: snowflake
      account: {{ env_var('SNOWFLAKE_ACCOUNT') }}
      user: {{ env_var('SNOWFLAKE_USER') }}
      password: {{ env_var('SNOWFLAKE_PASSWORD') }}
      warehouse: {{ env_var('SNOWFLAKE_WAREHOUSE') }}
      database: production
      role: accountadmin
      concurrent_tasks: 4
      register_comments: True
      pre_ping: False
      pretty_sql: False
    state_connection:
      type: postgres
      host: {{ env_var('SUPABASE_HOST') }}
      user: {{ env_var('SUPABASE_USER') }}
      password: {{ env_var('SUPABASE_PASSWORD') }}
      port: {{ env_var('SUPABASE_PORT') | int }}
      database: {{ env_var('SUPABASE_DB') }}

default_gateway: sfprod

default_target_environment: {{ env_var('SNOWFLAKE_USER') }}
environment_catalog_mapping:
  {{ env_var('SNOWFLAKE_USER') }}: development
  prod: production
# environment_suffix_target: table
# physical_schema_mapping:
#   '.*': '@schema'

model_defaults:
  dialect: snowflake
  start: 2025-03-18
