name: Ingest Yelp data into Snowflake

on:
  workflow_dispatch:
    inputs:
        version:
          description: "Release version to download"
          required: true

jobs:
  download-and-upload-to-snowflake:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install snowflake-connector-python

      - name: Set release var
        id: vars
        run: echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV

      - name: Get release assets
        run: |
          FILE_PATTERN="*_3.zip"
          RELEASE_URL="https://api.github.com/repos/${{ github.repository }}/releases/tags/${{ steps.vars.outputs.RELEASE_VERSION }}"
          curl -s "$RELEASE_URL" | jq -r '.assets[] | select(.name | test("'"$FILE_PATTERN"'")) | .browser_download_url' > download_urls.txt
          echo "Files to download:"
          cat download_urls.txt

      - name: Download datasets
        env:
          DATASET_FILE_NAME: yelp_dataset_
          TARGET_DIR: dataset
        run: |
          cd dags/ingestion
          while IFS= read -r url; do
            wget -P ./dataset/ "$url"
          done < download_urls.txt
          echo "Downloaded files:"
          ls -l ${TARGET_DIR}

      - name: Extract datasets
        run: |
          unzip ${TARGET_DIR}/${DATASET_FILE_NAME}3.zip -d ${TARGET_DIR}

      - name: Upload to Snowflake tables
        env:
          SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWFLAKE_PASSWORD }}
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
          SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SNOWFLAKE_DATABASE: raw
          SNOWFLAKE_SCHEMA: yelp
          SNOWFLAKE_STAGE: yelp_ingestion_stage
        run: |
          python yelp_data_ingestion.py

# https://github.com/${OWNER}/${REPO}/releases/download/${TAG}/${DATASET_FILE_NAME}1.zip \
# https://github.com/${OWNER}/${REPO}/releases/download/${TAG}/${DATASET_FILE_NAME}2.zip \

# unzip ${TARGET_DIR}/${DATASET_FILE_NAME}1.zip -d ${TARGET_DIR}
# unzip ${TARGET_DIR}/${DATASET_FILE_NAME}2.zip -d ${TARGET_DIR}
